id = "zed-extension-viskum"
name = "Viskum Tree Sitter"
version = "0.0.1"
schema_version = 1
authors = ["Tobias Viskum <tobias.t.viskum@gmail.com>"]
description = "This parses a viskum language with tree sitter"
repository = "https://github.com/TobiasViskum/zed-extension-viskum"

[grammars.viskum]
repository = "https://github.com/TobiasViskum/tree-sitter-viskum"
rev = "d6f877c93efca28c396d08ac249789a60e640888"
